name: read_right_app

version: 
  1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path: ^1.9.0
  provider: ^6.1.0
  firebase_core: ^4.2.1
  firebase_database: ^12.0.4
  firebase_auth: ^6.1.2
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.5
  confetti: ^0.7.0

  

flutter:
  uses-material-design: true
  assets: 
    - assets/seed_words.csv
    - assets/seed_words_with_sentences_complete.csv
dev_dependencies:
  flutter_test: any
