name: read_right_app

version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path: ^1.9.0
  provider: ^6.1.0
  firebase_core: ^4.2.1
  firebase_database: ^12.0.4
  firebase_auth: ^6.1.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0
  uuid: ^4.5.1
  path_provider: ^2.1.4
  share_plus: ^12.0.1
  record: ^6.1.2
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/seed_words.csv
    - assets/seed_words_with_sentences_complete.csv
    - assets/SourceImages/character1.png
    - assets/SourceImages/character2.png
    - assets/SourceImages/character3.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  record_linux: ^1.2.1
  share_plus_platform_interface: ^6.1.0
